### ISSUE TITLE
Request for addition to actionbar settings

### ISSUE THREAD

**Issue by Kewlie** [Hydra-Mods/HydraUI#102]
heya hydra, i would like to know if u might be able to add an option to "hide the VehicleUI that apears while mounting a vehicle as i find it ugly and would rather just have the buttons on actionbar 1 that has paged

i have noticed all other oaction bars hide, well all except the stance bar
![image](https://user-images.githubusercontent.com/34406478/235087481-219aa4de-6c08-4b25-a491-c38c0ecf9653.png)

as u can see from the screen snip  the vehicleui is just out of place and it's pointless moving the ui to fit around the vehicleui that apears while doing a quest

again thanks alot for all your hard work on the project

**Comment by Kewlie** [comment]
sorry forgot to add im playing wrath classic

**Comment by Hydra-Mods** [comment]
I'll see what I can do for  this

**Comment by Hydra-Mods** [comment]
This was added to 2.05
