### ISSUE TITLE
HydraUI is not working correctly on WOW Classic

### ISSUE THREAD

**Issue by ETERNALTIGGRAIN** [Hydra-Mods/HydraUI#105]
Hi, I just started playing WOW again and so had been re-downloading and updating various add-ons. I had re-downloaded HydraUI and for some reason, it's not functioning correctly. When I activate it only certain parts function. Such as the chatbox modules and the other box that's on the side. the action bars on the other hand stay Blizzard action bars, The player and target boxes are blizzards art style as is the minimap. I'm not sure why this is happening. When I checked if this same issue is happening on Wrath Classic, it's not. Everything appears to be functioning the way it's supposed to. I turned off many of my addons on Classic and still have the same problem and I'm also getting the error message.

Message: Interface\AddOns\HydraUI\Elements\Chat.lua:1137: attempt to index field 'GUILD_ACHIEVEMENT' (a nil value)
Time: Tue May  9 02:39:06 2023
Count: 1
Stack: Interface\AddOns\HydraUI\Elements\Chat.lua:1137: attempt to index field 'GUILD_ACHIEVEMENT' (a nil value)
[string "@Interface\AddOns\HydraUI\Elements\Chat.lua"]:1137: in function `SetChatTypeInfo'
[string "@Interface\AddOns\HydraUI\Elements\Chat.lua"]:1172: in function `Load'
[string "@Interface\AddOns\HydraUI\Elements\Initialize.lua"]:75: in function `LoadModules'
[string "@Interface\AddOns\HydraUI\Elements\Initialize.lua"]:156: in function <Interface\AddOns\HydraUI\Elements\Initialize.lua:143>

Locals: self = HydraUI Chat {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface\SharedXML\Backdrop.lua:144
 GetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:382
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:414
 Middle = HydraUIChatFrameMiddle {
 }
 Bottom = HydraUIChatFrameBottom {
 }
 RemoveTextures = <table> {
 }
 ApplyBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:274
 Top = HydraUIChatFrameTop {
 }
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:339
 SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:258
 OverrideAddMessage = <function> defined @Interface\AddOns\HydraUI\Elements\Chat.lua:630
 Install = <function> defined @Interface\AddOns\HydraUI\Elements\Chat.lua:953
 CreateCopyWindow = <function> defined @Interface\AddOns\HydraUI\Elements\Chat.lua:442
 OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:174
 HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:270
 GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:180
 Mover = <unnamed> {
 }
 SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:206
 CreateChatWindow = <function> defined @Interface\AddOns\HydraUI\Elements\Chat.lua:241
 EditBox = <unnamed> {
 }
 StyleChatFrame = <function> defined @Interface\AddOns\HydraUI\Elements\Chat.lua:636
 AddMessageFilters = <function> defined @Interface\AddOns\HydraUI\Elements\Chat.lua:1063
 Load = <function> defined @Interface\AddOns\HydraUI\Elements\Chat.lua:1152
 Name = "Chat"
 StyleChatFrames = <function> defined @Interface\AddOns\HydraUI\Elements\Chat.lua:915
 SetupPieceVisuals = <function> defined @Interface\SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:391
 SetChatTypeInfo = <function> defined @Interface\AddOns\HydraUI\Elements\Chat.lua:1083
 MoveChatFrames = <function> defined @Interface\AddOns\HydraUI\Elements\Chat.lua:839
}
(*temporary) = nil
(*temporary) = <table> {
 b = 1
 sticky = 0
 g = 0.666667
 r = 0
}
(*temporary) = nil
(*temporary) = "attempt to index field 'GUILD_ACHIEVEMENT' (a nil value)"
Language = <table> {
}

**Comment by Hydra-Mods** [comment]
Thank you for the report, I applied a fix and version 2.07 should be good to go. Welcome back and thanks for using HydraUI!
