### ISSUE TITLE
Some of the UI isn't functioning properly and I keep getting error messages

### ISSUE THREAD

**Issue by ETERNALTIGGRAIN** [Hydra-Mods/HydraUI#112]
For some reason, some of the UI like the Map and buffs aren't movable right now when I try and Toggle. Plus I keep getting these error messages like when I try to use abilities on my character, no matter what.
Here is the error message.
Message: .../Elements/Libraries/oUF/elements/powerprediction.lua:70: attempt to index upvalue 'ALT_MANA_BAR_PAIR_DISPLAY_INFO' (a nil value)
Time: Thu Jul 13 15:42:28 2023
Count: 75
Stack: .../Elements/Libraries/oUF/elements/powerprediction.lua:70: attempt to index upvalue 'ALT_MANA_BAR_PAIR_DISPLAY_INFO' (a nil value)
[string "@Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/powerprediction.lua"]:70: in function <.../Elements/Libraries/oUF/elements/powerprediction.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?

Locals: self = HydraUI Player {
 0 = <userdata>
 UNIT_MAXPOWER = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/power.lua:258
 HealthLeft = FontString {
 }
 UNIT_SPELLCAST_EMPOWER_START = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/castbar.lua:126
 unitEvents = <table> {
 }
 CastAnchor = HydraUI Casting Bar {
 }
 UNIT_MAXHEALTH = <table> {
 }
 UNIT_POWER_FREQUENT = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/power.lua:258
 PowerPrediction = <table> {
 }
 UNIT_POWER_BAR_SHOW = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/power.lua:258
 UNIT_SPELLCAST_NOT_INTERRUPTIBLE = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/castbar.lua:325
 PLAYER_REGEN_DISABLED = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/combatindicator.lua:58
 style = "HydraUI"
 PvPIndicator = Texture {
 }
 UNIT_EXITED_VEHICLE = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/ouf.lua:53
 Debuffs = HydraUI PlayerDebuffs {
 }
 UNIT_HEAL_PREDICTION = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/healthprediction.lua:10
 unit = "player"
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/castbar.lua:215
 HealBar = StatusBar {
 }
 UNIT_SPELLCAST_STOP = <table> {
 }
 UNIT_AURA = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/auras.lua:323
 ThreatIndicator = Frame {
 }
 Buffs = HydraUI PlayerBuffs {
 }
 __tags = <table> {
 }
 UNIT_ENTERED_VEHICLE = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/ouf.lua:53
 INCOMING_RESURRECT_CHANGED = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/resurrectindicator.lua:60
 UNIT_SPELLCAST_INTERRUPTIBLE = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/castbar.lua:325
 __elements = <table> {
 }
 Power = StatusBar {
 }
 HolyPower = HydraUI PlayerHolyPower {
 }
 Mover = Frame {
 }
 UNIT_THREAT_SITUATION_UPDATE = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/threatindicator.lua:92
 UNIT_HEALTH = <table> {
 }
 Health = StatusBar {
 }
 ResourceAnchor = HydraUI Class Resource {
 }
 AuraParent = HydraUI PlayerHolyPower {
 }
 PowerRight = FontString {
 }
 PLAYER_REGEN_ENABLED = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/combatindicator.lua:58
 HONOR_LEVEL_UPDATE = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/pvpindicator.lua:109
 Portrait = PlayerModel {
 }
 SmoothBar = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/smooth.lua:35
 UNIT_FACTION = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/pvpindicator.lua:109
 UNIT_HEAL_ABSORB_AMOUNT_CHANGED = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/healthprediction.lua:10
 UNIT_SPELLCAST_START = <table> {
 }
 UNIT_ABSORB_AMOUNT_CHANGED = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/healthprediction.lua:10
 GROUP_ROSTER_UPDATE = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/leaderindicator.lua:59
 PLAYER_ENTERING_WORLD = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/ouf.lua:53
 ResurrectIndicator = Texture {
 }

**Comment by ETERNALTIGGRAIN** [comment]
Here's another error I got this is the first one:
Message: .../Elements/Libraries/oUF/elements/powerprediction.lua:70: attempt to index upvalue 'ALT_MANA_BAR_PAIR_DISPLAY_INFO' (a nil value)
Time: Thu Jul 13 15:20:33 2023
Count: 1
Stack: .../Elements/Libraries/oUF/elements/powerprediction.lua:70: attempt to index upvalue 'ALT_MANA_BAR_PAIR_DISPLAY_INFO' (a nil value)
[string "@Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/powerprediction.lua"]:70: in function <.../Elements/Libraries/oUF/elements/powerprediction.lua:52>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/HydraUI/Elements/Libraries/oUF/ouf.lua"]:201: in function `UpdateAllElements'
[string "@Interface/AddOns/HydraUI/Elements/UnitFrames/UnitFrames.lua"]:769: in function `Load'
[string "@Interface/AddOns/HydraUI/Elements/Initialize.lua"]:75: in function `LoadModules'
[string "@Interface/AddOns/HydraUI/Elements/Initialize.lua"]:156: in function <Interface/AddOns/HydraUI/Elements/Initialize.lua:143>

Locals: self = HydraUI Player {
 0 = <userdata>
 UNIT_MAXPOWER = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/power.lua:258
 HealthLeft = FontString {
 }
 UNIT_SPELLCAST_EMPOWER_START = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/castbar.lua:126
 unitEvents = <table> {
 }
 CastAnchor = HydraUI Casting Bar {
 }
 UNIT_MAXHEALTH = <table> {
 }
 UNIT_POWER_FREQUENT = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/power.lua:258
 PowerPrediction = <table> {
 }
 UNIT_POWER_BAR_SHOW = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/power.lua:258
 UNIT_SPELLCAST_NOT_INTERRUPTIBLE = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/castbar.lua:325
 PLAYER_REGEN_DISABLED = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/combatindicator.lua:58
 style = "HydraUI"
 PvPIndicator = Texture {
 }
 UNIT_EXITED_VEHICLE = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/ouf.lua:53
 Debuffs = HydraUI PlayerDebuffs {
 }
 UNIT_HEAL_PREDICTION = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/healthprediction.lua:10
 unit = "player"
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/castbar.lua:215
 HealBar = StatusBar {
 }
 UNIT_SPELLCAST_STOP = <table> {
 }
 UNIT_AURA = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/auras.lua:323
 ThreatIndicator = Frame {
 }
 Buffs = HydraUI PlayerBuffs {
 }
 __tags = <table> {
 }
 UNIT_ENTERED_VEHICLE = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/ouf.lua:53
 INCOMING_RESURRECT_CHANGED = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/resurrectindicator.lua:60
 UNIT_SPELLCAST_INTERRUPTIBLE = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/castbar.lua:325
 __elements = <table> {
 }
 Power = StatusBar {
 }
 HolyPower = HydraUI PlayerHolyPower {
 }
 Mover = Frame {
 }
 UNIT_THREAT_SITUATION_UPDATE = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/threatindicator.lua:92
 UNIT_HEALTH = <table> {
 }
 Health = StatusBar {
 }
 ResourceAnchor = HydraUI Class Resource {
 }
 AuraParent = HydraUI PlayerHolyPower {
 }
 PowerRight = FontString {
 }
 PLAYER_REGEN_ENABLED = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/combatindicator.lua:58
 HONOR_LEVEL_UPDATE = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/pvpindicator.lua:109
 Portrait = PlayerModel {
 }
 SmoothBar = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/smooth.lua:35
 UNIT_FACTION = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/pvpindicator.lua:109
 UNIT_HEAL_ABSORB_AMOUNT_CHANGED = <function> defined @Interface/AddOns/HydraUI/Elements/Libraries/oUF/elements/healthprediction.lua:10
 UNIT_SPELLCAST_START = <table>

**Comment by Hydra-Mods** [comment]
Thank you for the report, the new version will fix these errors
