### ISSUE TITLE
Selling items error

### ISSUE THREAD

**Issue by manov32** [Hydra-Mods/HydraUI#113]
Hello! Hope you are doing well! 

I'm using hydraui from few days and every time when I go to vendor to sell my items I get this error: 
Date: 2023-07-13 16:49:48
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/HydraUI/Elements/Cooldowns.lua line 218:
   attempt to call global 'GetContainerItemID' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: GetContainerItemID()
   [string "@Interface/AddOns/HydraUI/Elements/Cooldowns.lua"]:218:
      Interface/AddOns/HydraUI/Elements/Cooldowns.lua:217
   [string "=[C]"]: UseContainerItem()
   [string "@Interface/FrameXML/ContainerFrame_Shared.lua"]:1273:
      Interface/FrameXML/ContainerFrame_Shared.lua:1233
   [string "=[C]"]: ContainerFrameItemButton_OnClick()
   [string "*ContainerFrame.xml:165_OnClick"]:13:
      [string "*ContainerFrame.xml:165_OnClick"]:1
Locals:
(*temporary) = "RightButton"
(*temporary) = false
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  AucAdvanced, v3.4.6931 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucScanData, v3.4.6908 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  Auctionator, v1.1.13
  Bartender4, v4.14.10
  BeanCounter, v3.4.6933 (SwimmingSeadragon)
  DBMCore, v71676ab
  DBMStatusBarTimers, v71676ab
  DBMVPVEM, vb201a88
  Details, v#Details.20230520.11023.151-76-g9a49918
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DruidBuffs, v2.4.2
  FontDamageChanger, v
  GatherMate2, v1.47-classic
  HydraUI, v1.973
  LeatrixMaps, v3.0.140
  MinimapButtonButton, v1.17.2
  MobInfo2, v10.1.15
  Pawn, v2.8.3
  Questie, v8.8.1
  RareScanner, v3.4.2.2
  Stubby, v3.4.6920 (SwimmingSeadragon)
  TacoTip, v0.4.2
  TitanClassic, v1.5.9.30402
  TitanClassicAmmo, v1.5.9.30402
  TitanClassicBag, v1.5.9.30402
  TitanClassicClock, v1.5.9.30402
  TitanClassicGold, v1.5.9.30402
  TitanClassicGuild, v1.0.5
  TitanClassicLocation, v1.5.9.30402
  TitanClassicLootType, v1.5.9.30402
  TitanClassicPerformance, v1.5.9.30402
  TitanClassicRegen, v1.5.9.30402
  TitanClassicRepair, v1.5.9.30402
  TitanClassicVolume, v1.5.9.30402
  TitanClassicXP, v1.5.9.30402
  TitanHonorBw, v1.0.5
  TomTom, vv3.5.1-release
  TradeSkillMaster, vv4.13.1
  TradeSkillMasterAppHelper, vv4.12.2
  WhereToGatherClassic, v3.5
  BlizRuntimeLib_enUS v3.4.2.30402 <none>
  (ck=6bd)

Not sure if one of my other addons is is the cause of it, or it is some error in hydraui? If someone can help me I would be really grateful!

**Comment by Hydra-Mods** [comment]
Hey there! version 1.973 is massively out of date. To keep up to date with new versions and fixes please use one of the links that I directly update to;

Curse - https://www.curseforge.com/wow/addons/hydraui
WeakAuras - https://addons.wago.io/addons/hydraui

Or you can keep up to date directly off this git repo
