### ISSUE TITLE
Having some button functionality issues.

### ISSUE THREAD

**Issue by ETERNALTIGGRAIN** [Hydra-Mods/HydraUI#114]
This one error keeps popping up and it's making certain buttons not function unless I click them manually and even then it's hit or miss even with reloading it's acting funky. Here's the error message.

Message: bad argument #4 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
Time: Fri Jul 21 13:45:44 2023
Count: 1
Stack: bad argument #4 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateTexture'
[string "@Interface/AddOns/HydraUI/Elements/MiniMapButtons.lua"]:188: in function `SkinButtons'
[string "@Interface/AddOns/HydraUI/Elements/MiniMapButtons.lua"]:237: in function <Interface/AddOns/HydraUI/Elements/MiniMapButtons.lua:235>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by Hydra-Mods** [comment]
Thanks for the report, version 2.13 should fix this issue
