### ISSUE TITLE
In Game Bug

### ISSUE THREAD

**Issue by klyxmaster** [Hydra-Mods/HydraUI#116]
Not sure where to put this, so here goes....

ID: 1
Error occured in: Global
Count: 1
Message: HydraUI Vehicle:CreateFontString(): Couldn't find inherited node "7"
Debug:
   [string "=[C]"]: CreateFontString()
   [string "@Interface/AddOns/HydraUI/Elements/Taxi.lua"]:57: Load()
   [string "@Interface/AddOns/HydraUI/Elements/Initialize.lua"]:74: LoadModules()
   [string "@Interface/AddOns/HydraUI/Elements/Initialize.lua"]:153:
      Interface/AddOns/HydraUI/Elements/Initialize.lua:142
Locals:
(*temporary) = "HydraUI Vehicle:CreateFontString(): Couldn't find inherited node "7""

**Comment by Hydra-Mods** [comment]
Thanks for the report, this has been fixed
