### ISSUE TITLE
Error caused by casting LifeBloom in Season of Discovery

### ISSUE THREAD

**Issue by Kewlie** [Hydra-Mods/HydraUI#119]
please see attached error 

Lifebloom rune client version 1.15.0 

tooltip for reference
![image](https://github.com/Hydra-Mods/HydraUI/assets/34406478/a58f03a0-2b97-4fac-8d3c-9ab165aee446)

5x ...ddOns/HydraUI/Elements/Libraries/LibHealComm-4.0-107.lua:818: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
[string "@HydraUI/Elements/Libraries/LibHealComm-4.0-107.lua"]:818: in function <...ddOns/HydraUI/Elements/Libraries/LibHealComm-4.0.lua:807>
[string "@HydraUI/Elements/Libraries/LibHealComm-4.0-107.lua"]:967: in function <...ddOns/HydraUI/Elements/Libraries/LibHealComm-4.0.lua:965>
[string "@HydraUI/Elements/Libraries/LibHealComm-4.0-107.lua"]:2706: in function `?'
[string "@HydraUI/Elements/Libraries/LibHealComm-4.0-107.lua"]:3348: in function <...ddOns/HydraUI/Elements/Libraries/LibHealComm-4.0.lua:3346>

Locals:
spellData = <table> {
 levels = <table> {
 }
 bomb = <table> {
 }
 coeff = 0.520000
 interval = 1
 ticks = 7
 averages = <table> {
 }
 dhCoeff = 0.343350
}
spellName = "Lifebloom"
spellID = 408124
spellRank = nil
average = nil
requiresLevel = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 17
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'requiresLevel' (a nil value)"
type = <function> defined =[C]:-1
min = <function> defined =[C]:-1
playerLevel = 17

**Comment by Kewlie** [comment]
so just installed the new version from curse "updated libraries" but still didn't fix the issue here is a wowhead link to the spell

https://www.wowhead.com/classic/spell=409824/lifebloom

i will also post this in the elvui github hopefully someone can find a fix thanks for all your hard work so far hydra :D

**Comment by CadoCat** [comment]
Likely because the Healcomm lib hasn't been updated for SoD runes.

Try replacing the LibHealComm in your classic_era folder with the attached and let me know how you go.
[LibHealComm-4.0.zip](https://github.com/Hydra-Mods/HydraUI/files/13631306/LibHealComm-4.0.zip)

**Comment by CadoCat** [comment]
I added the wrong spellID. Edit the file.

Line 86 should be 408124, not 409824.

**Comment by CadoCat** [comment]
[LibHealComm-4.0-new.zip](https://github.com/Hydra-Mods/HydraUI/files/13644383/LibHealComm-4.0-new.zip)

Try this one

**Comment by Kewlie** [comment]
thanks mate, i just edited it as stated and now understand that section of
the library file

thanks again

**Comment by CadoCat** [comment]
Did it resolve it?

**Comment by Kewlie** [comment]
yes mate it did thanks

**Comment by Kewlie** [comment]
this issue should be able to be resolved if hydra has the time to convert healcomm lib into the classic heal prediction API

the fix posted by cado is a temporary fix that will prevent errors but also cause Lib HealComm to provide wrong values

if anyone needs a copy of the lib healcomm file use this:

[LibHealComm-4.0.zip](https://github.com/Hydra-Mods/HydraUI/files/14733870/LibHealComm-4.0.zip)

paste the containing LUA file in the directory World of Warcraft\_Classic_Era_\Interface\Addons\HydraUI\Elements\Libraries\
