### ISSUE TITLE
Tooltips.lua ERROR

### ISSUE THREAD

**Issue by derschneidertom** [Hydra-Mods/HydraUI#15]
new error with version 1.47, 1.48, 1.49 and so on,,,
![WoWScrnShot_072320_215233](https://user-images.githubusercontent.com/52461892/88415708-39d6c900-cddf-11ea-933c-07bfd512d79f.jpg)

**Comment by Hydra-Mods** [comment]
Does this error continue if you disable other addons except vUI? it looks like an addon conflict

**Comment by derschneidertom** [comment]
Yes, that is the Problem and why i wrote you...i disable all my addons and it still happend. i also delete them all and copy my backup back. i also deleted them and reinstalled them. now i have delete vUI...i was always lucky with this ui because it is nice and realy small and much better then ElvUI andsoon...let me know if you have a new version, i will test it :-)
here my addons:
"!MoncaiCompare,Ace3,ACP,AzeritePowerWeights,BagBrother,Bagnon,Bartender4,BestKeystone,Buttons,GatherMate2,Gnosis,Mapster,Masque,Pawn,RareScanner,Recount,SellJunk,ShadowedUF_Options,ShadowedUnitFrames,Simulationcraft,SpellFlash,SpellFla,shCore,TinyTooltip"

**Comment by Hydra-Mods** [comment]
I'll investigate this then today
