### ISSUE TITLE
Lua errors on start (shadowlands beta)

### ISSUE THREAD

**Issue by bbackbone** [Hydra-Mods/HydraUI#16]
Message: Interface\AddOns\vUI\Elements\Cooldowns.lua:63: attempt to call method 'SetBackdrop' (a nil value)
Time: Mon Jul 27 19:15:24 2020
Count: 1
Stack: Interface\AddOns\vUI\Elements\Cooldowns.lua:63: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\vUI\Elements\Cooldowns.lua"]:63: in main chunk

Locals: vUI = <unnamed> {
 0 = <userdata>
 ProfileMetadata = <table> {
 }
 Migrate = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:485
 BindSavedVariable = <function> defined @Interface\AddOns\vUI\Initialize.lua:357
 SetProfileValue = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:176
 CopyProfile = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:431
 LoadPlugins = <function> defined @Interface\AddOns\vUI\Initialize.lua:186
 MigrateKey = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:473
 SetColorEntry = <function> defined @Interface\AddOns\vUI\Elements\Colors.lua:13
 AddDataText = <function> defined @Interface\AddOns\vUI\Elements\DataTexts\DataTexts.lua:135
 DeleteProfile = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:248
 UnitFrames = <table> {
 }
 FormatLinks = <function> defined @Interface\AddOns\vUI\Elements\Chat\Chat.lua:41
 DebuffColors = <table> {
 }
 UserProfileKey = "Bobeek:The Maw"
 TimerPool = <table> {
 }
 StringToPosition = <function> defined @Interface\AddOns\vUI\Elements\Move.lua:18
 UserName = "Bobeek"
 MigrateGlobal = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:481
 UpdateColors = <function> defined @Interface\AddOns\vUI\Elements\Colors.lua:100
 ClassColors = <table> {
 }
 SendAlert = <function> defined @Interface\AddOns\vUI\Elements\Alerts.lua:205
 UpdateProfileList = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:27
 GetProfileList = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:188
 ClearPopup = <function> defined @Interface\AddOns\vUI\Elements\Popup.lua:185
 UpdateZoneColors = <function> defined @Interface\AddOns\vUI\Elements\Colors.lua:52
 MovingActive = false
 MigrateData = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:504
 UpdateoUFColors = <function> defined @Interface\AddOns\vUI\Elements\Libraries\oUF\colors.lua:112
 MergeWithDefaults = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:280
 UpdatePowerColors = <function> defined @Interface\AddOns\vUI\Elements\Colors.lua:62
 ResetAllMovers = <function> defined @Interface\AddOns\vUI\Elements\Move.lua:99
 IsMoved = <function> defined @Interface\AddOns\vUI\Elements\Move.lua:103
 ShortValue = <function> defined @Interface\AddOns\vUI\Initialize.lua:318
 ResetMovers = <function> defined @Interface\AddOns\vUI\Elements\Move.lua:82
 PreserveSettings = <table> {
 }
 GetActiveProfileName = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:49
 Plugins = <table> {
 }
 ApplyProfile = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:299
 ToggleMovers = <function> defined @Interface\AddOns\vUI\Elements\Move.lua:52
 UpdateClassColors = <function> defined @Interface\AddOns\vUI\Elements\Colors.lua:26
 CountUnusedProfiles = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:359
 CreateMover = <function> defined @Interface\AddOns\vUI\Elements\Move.lua:164
 FrameDefaults = <table> {
 }
 MovingFrames = <table> {
 }
 LoadPlugin = <function> defined @Interface\AddOns\vUI\Initialize.lua:173
 DisplayPopup = <function> defined @Interface\AddOns\vUI\Elements\Popup.lua:189
 Backdrop = <table> {
 }
 UpdateScreenSize = <function> defined @Interface\AddOns\vUI\Initialize.lua:237
 CreateProfileData = <function> defined @Interface\AddOns\vUI\Elements\Profiles.lua:80
 UpdateComboColors = <function> defined @Interface\AddOns\vUI\Elements\Colors.lua:91
 SetScale = <function> defined @Interface\AddOns\vUI\Initialize.lua:251
 UpdateReactionColors = <function> defined @Interface\AddOns\vUI\Elements\Colors.lua:41
 PositionToString = <function> defined @Interface\AddOns\v
![vui](https://user-images.githubusercontent.com/68083359/88576631-a2bb7c80-d03d-11ea-9f85-82d93110ff1f.png)

**Comment by Hydra-Mods** [comment]
The live build of vUI does not work for the Shadowlands beta, I currently host a functional version on my Patreon for pledges of $5 or more
