### ISSUE TITLE
Clock displayed in 12h format only

### ISSUE THREAD

**Issue by vadymkedych** [Hydra-Mods/HydraUI#46]
After relog, it's always 12h format even if in settings it set to 24h

**Comment by Hydra-Mods** [comment]
Hello there!

Are you changing the setting in /hui > Data Texts > Enable 24 Hour Time?

**Comment by vadymkedych** [comment]
Hi. Data texts are empty for some reason.
![HUI_data_texts](https://user-images.githubusercontent.com/22193315/146055235-4a639405-6383-40cc-ac1e-d740a6b12aee.png)

**Comment by Hydra-Mods** [comment]
An update has been made to correct this issue
