### ISSUE TITLE
Text overflow the frame when open linked quest from chat

### ISSUE THREAD

**Issue by vadymkedych** [Hydra-Mods/HydraUI#50]
It happens only once after the session start. The second time and more you click the quest in chat everything is fine.
![Quest](https://user-images.githubusercontent.com/22193315/189452564-447bc3a9-d774-4321-b103-8e02a5c305bc.png)

**Comment by Hydra-Mods** [comment]
Thank you for the report, I was able to reproduce this error and fix it for the next version 🙂
