### ISSUE TITLE
Objective Tracker Wrath Classic

### ISSUE THREAD

**Issue by Kewlie** [Hydra-Mods/HydraUI#52]
i see that there are movers for objective trackers but i believe for wrath they renamed it there for your movers are not moving said frame, going by messing around with move anything addon i believe it's now called "QuestWatchFrame"

currently objective tracker / quest watch is partially hidden under the minimap especially if if the minimap is set larger via options

**Comment by Hydra-Mods** [comment]
Thank you for the report, I've fixed the quest watch mover for the next version 🙂
