### ISSUE TITLE
Calendar in Wotlk

### ISSUE THREAD

**Issue by CadoCat** [Hydra-Mods/HydraUI#55]
So something that came up in the discord is the calendar for Wrath. I've managed to fix this for myself but I assume my fix would possibly affect other versions of the game (I only play wrath). Primarily, my fix was applied in the minimap.lua:

```
--	self:Disable(MinimapCluster)
	self:Disable(MinimapBorder)
	self:Disable(MinimapBorderTop)
	self:Disable(MinimapZoomIn)
	self:Disable(MinimapZoomOut)
	self:Disable(MinimapNorthTag)
	self:Disable(MiniMapWorldMapButton)
	self:Disable(MiniMapMailBorder)
	self:Disable(TimeManagerClockButton)
	
	MinimapCluster:ClearAllPoints()
	MinimapCluster:SetFrameStrata("MEDIUM")
	MinimapCluster:SetSize(24, 24)
	MinimapCluster:SetPoint("TOPRIGHT", 1, -1)
	MinimapCluster:SetFrameLevel(Minimap:GetFrameLevel() + 1)

	
	if GameTimeFrame then
		GameTimeFrame:ClearAllPoints()
		GameTimeFrame:SetPoint("TOPRIGHT", Minimap , 1, -1)
		if (not Settings["minimap-show-calendar"]) then
			GameTimeFrame:Hide()
		end
	end
```

As I found the GameTimeFrame was attached to the MinimapCluster, I couldn't disable it. My solution was to leave it hidden in the corner. 

The other problem was the switch for it in the options. By removing The HydraUI.isMainline check, I had the option again in Wrath.

```
--	if HydraUI.IsMainline then
		left:CreateSwitch("minimap-show-calendar", Settings["minimap-show-calendar"], Language["Enable Calendar"], Language["Enable the calendar button on the minimap"], UpdateShowCalendar)
--	end
```

My understanding is that the check is for retail, I'm not sure how to perform the same check for Wrath, so I just removed it.

Hope this helps with implementing a solution.

**Comment by Hydra-Mods** [comment]
Appreciate the report, I didn't notice that the calendar was back in wrath. I've fixed this for the next release :)
