### ISSUE TITLE
Wotlk Classic Shaman totembar

### ISSUE THREAD

**Issue by Kewlie** [Hydra-Mods/HydraUI#60]
can we please get a mover for the shaman totem bar that was introduced with wrath classic as it is currently un moveable i will post a pic

![image](https://user-images.githubusercontent.com/34406478/192441071-069d1c6e-be75-48a7-9424-b238291cb0cc.png)

as you can see it looks to be behind the chat window but if i move the chat out of the way  i find that i can't move it

![image](https://user-images.githubusercontent.com/34406478/192441200-c3967803-a6e0-42ff-a35b-ffdeb634c7b9.png)

**Comment by Hydra-Mods** [comment]
Thank you for the report, a mover will be coming soon

**Comment by Hydra-Mods** [comment]
This feature has been written now and will be in the next release. Thanks again for your suggestion!
