### ISSUE TITLE
DF lua errors on loading

### ISSUE THREAD

**Issue by NalarSVK** [Hydra-Mods/HydraUI#63]
Hello,

I got recomendation on Discord to post errors here, since UI is marked as compatible with 10.0.2, i decied to givie it a try on DF beta. UI will not load at all and I got following errors:

1.) 
`Message: ...rface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua:54: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
Time: Thu Sep 29 14:20:01 2022
Count: 1
Stack: ...rface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua:54: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua"]:54: in function `Update'
[string "@Interface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua"]:72: in function `Enable'
[string "@Interface/AddOns/HydraUI/Elements/DataTexts/DataTexts.lua"]:109: in function `SetDataText'
[string "@Interface/AddOns/HydraUI/Elements/Chat.lua"]:1416: in function `AddDataTexts'
[string "@Interface/AddOns/HydraUI/Elements/Chat.lua"]:1457: in function `Load'
[string "@Interface/AddOns/HydraUI/Elements/Initialize.lua"]:74: in function `LoadModules'
[string "@Interface/AddOns/HydraUI/Elements/Initialize.lua"]:153: in function <Interface/AddOns/HydraUI/Elements/Initialize.lua:142>

Locals: self = Frame {
 0 = <userdata>
 SetTooltip = <function> defined @Interface/AddOns/HydraUI/Elements/DataTexts/DataTexts.lua:27
 Name = "Window-Left"
 Highlight = Texture {
 }
 Enable = <function> defined @Interface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua:65
 Text = FontString {
 }
 Update = <function> defined @Interface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua:49
 Disable = <function> defined @Interface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua:75
}
TotalSlots = 0
FreeSlots = 0
(for index) = 0
(for limit) = 4
(for step) = 1
i = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call upvalue 'GetContainerNumSlots' (a nil value)"
NUM_BAG_SLOTS = 4
GetContainerNumSlots = nil
GetContainerNumFreeSlots = nil
Settings = <table> {
 ab-bar1-button-gap = 2
 color-reaction-7 = "009919"
 cooldowns-size = 60
 party-show-debuffs = true
 ab-pet-button-size = 32
 unitframes-player-power-left = "[HealthValues:Short]"
 chat-enable-discord-links = true
 color-reaction-2 = "BF4400"
 color-holy-power = "F2E599"
 unitframes-target-cast-width = 250
 error-font-size = 16
 auras-row-spacing = 16
 ab-pet-per-row = 1
 party-font-flags = ""
 raid-out-of-range = 50
 party-spacing = 2
 color-casting-success = "4C9900"
 target-enable-portrait = false
 ab-bar1-button-max = 12
 ab-bar4-alpha = 100
 party-in-range = 100
 auras-count-color = "FFFFFF"
 ab-pet-hover = false
 ab-bar4-button-gap = 2
 ab-bar3-hover = false
 unitframes-target-enable-castbar = true
 unitframes-boss-health-reverse = false
 chat-tab-font = "Roboto"
 right-window-size = "SINGLE"
 ui-widget-color = "FFC44D"
 color-combo-2 = "FFB266"
 minimap-size = 140
 reputation-progress-visibility = "ALWAYS"
 error-font-flags = ""
 raid-pets-health-height = 22
 profile-created-by = "Lamaxxka-Koranos"
 unitframes-boss-power-color = "POWER"
 player-overlay-alpha = 30
 unitframes-focus-power-smooth = true
 unitframes-pet-power-smooth = true
 ab-bar1-hover = false
 raid-max-columns = 8
 ab-bar2-button-size = 32
 ab-bar1-button-size = 32
 unitframes-targettarget-enable-power = true
 tracker-module-font-color = "FFE6C0"
 color-other = "FFECC1"
 color-combo-points = "FFF468"
 tooltips-font-flags = ""
 ui-border-thickness = 0
 color-combo-6 = "66FF66"
 chat-bubbles-font = "PT Sans"
 player-enable-pvp = true
 unitframes-focus-health-reverse = false
 nameplates-enable-target-indicator = true
 chat-tab-font-color-mouseover = "FFCE54"
 raid-health-orientation = "HORIZONTAL"
 color-mana = "477CB2"
 nameplates-buffs-direction = "LTR"
 ui-button-font-color = "FFC44D"
 chat-bubbles-enable = true
 unitframes-target-power-reverse = false
 color-arena = "FF1919"
 ui-title-font-size = 16
 experience-percent-visibility = "ALWAYS"
 color-reaction-5 = "009919"
 minimap-top-height = 28
 unitframes-boss-health-smooth = true
 color-death-knight = "C41F3B"
 nameplates-topleft-text = "[LevelColor][Level][Plus][ColorStop] [Name(20)]"
 minimap-bottom-fill = 100
 cooldowns-text = false
 ab-bar3-enable = true
 unitframes-focus-health-`

2.) `Message: ...rface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua:54: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
Time: Thu Sep 29 14:20:01 2022
Count: 1
Stack: ...rface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua:54: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua"]:54: in function `Update'
[string "@Interface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua"]:72: in function `Enable'
[string "@Interface/AddOns/HydraUI/Elements/DataTexts/DataTexts.lua"]:109: in function `SetDataText'
[string "@Interface/AddOns/HydraUI/Elements/Chat.lua"]:1416: in function `AddDataTexts'
[string "@Interface/AddOns/HydraUI/Elements/Chat.lua"]:1457: in function `Load'
[string "@Interface/AddOns/HydraUI/Elements/Initialize.lua"]:74: in function `LoadModules'
[string "@Interface/AddOns/HydraUI/Elements/Initialize.lua"]:153: in function <Interface/AddOns/HydraUI/Elements/Initialize.lua:142>

Locals: self = Frame {
 0 = <userdata>
 SetTooltip = <function> defined @Interface/AddOns/HydraUI/Elements/DataTexts/DataTexts.lua:27
 Name = "Window-Left"
 Highlight = Texture {
 }
 Enable = <function> defined @Interface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua:65
 Text = FontString {
 }
 Update = <function> defined @Interface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua:49
 Disable = <function> defined @Interface/AddOns/HydraUI/Elements/DataTexts/BagSlots.lua:75
}
TotalSlots = 0
FreeSlots = 0
(for index) = 0
(for limit) = 4
(for step) = 1
i = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call upvalue 'GetContainerNumSlots' (a nil value)"
NUM_BAG_SLOTS = 4
GetContainerNumSlots = nil
GetContainerNumFreeSlots = nil
Settings = <table> {
 ab-bar1-button-gap = 2
 color-reaction-7 = "009919"
 cooldowns-size = 60
 party-show-debuffs = true
 ab-pet-button-size = 32
 unitframes-player-power-left = "[HealthValues:Short]"
 chat-enable-discord-links = true
 color-reaction-2 = "BF4400"
 color-holy-power = "F2E599"
 unitframes-target-cast-width = 250
 error-font-size = 16
 auras-row-spacing = 16
 ab-pet-per-row = 1
 party-font-flags = ""
 raid-out-of-range = 50
 party-spacing = 2
 color-casting-success = "4C9900"
 target-enable-portrait = false
 ab-bar1-button-max = 12
 ab-bar4-alpha = 100
 party-in-range = 100
 auras-count-color = "FFFFFF"
 ab-pet-hover = false
 ab-bar4-button-gap = 2
 ab-bar3-hover = false
 unitframes-target-enable-castbar = true
 unitframes-boss-health-reverse = false
 chat-tab-font = "Roboto"
 right-window-size = "SINGLE"
 ui-widget-color = "FFC44D"
 color-combo-2 = "FFB266"
 minimap-size = 140
 reputation-progress-visibility = "ALWAYS"
 error-font-flags = ""
 raid-pets-health-height = 22
 profile-created-by = "Lamaxxka-Koranos"
 unitframes-boss-power-color = "POWER"
 player-overlay-alpha = 30
 unitframes-focus-power-smooth = true
 unitframes-pet-power-smooth = true
 ab-bar1-hover = false
 raid-max-columns = 8
 ab-bar2-button-size = 32
 ab-bar1-button-size = 32
 unitframes-targettarget-enable-power = true
 tracker-module-font-color = "FFE6C0"
 color-other = "FFECC1"
 color-combo-points = "FFF468"
 tooltips-font-flags = ""
 ui-border-thickness = 0
 color-combo-6 = "66FF66"
 chat-bubbles-font = "PT Sans"
 player-enable-pvp = true
 unitframes-focus-health-reverse = false
 nameplates-enable-target-indicator = true
 chat-tab-font-color-mouseover = "FFCE54"
 raid-health-orientation = "HORIZONTAL"
 color-mana = "477CB2"
 nameplates-buffs-direction = "LTR"
 ui-button-font-color = "FFC44D"
 chat-bubbles-enable = true
 unitframes-target-power-reverse = false
 color-arena = "FF1919"
 ui-title-font-size = 16
 experience-percent-visibility = "ALWAYS"
 color-reaction-5 = "009919"
 minimap-top-height = 28
 unitframes-boss-health-smooth = true
 color-death-knight = "C41F3B"
 nameplates-topleft-text = "[LevelColor][Level][Plus][ColorStop] [Name(20)]"
 minimap-bottom-fill = 100
 cooldowns-text = false
 ab-bar3-enable = true
 unitframes-focus-health-`

**Comment by Hydra-Mods** [comment]
Thank you for the report, DF is still a work in progress during the beta phases :)
