### ISSUE TITLE
The chat fills with dummy frames on each UI reload

### ISSUE THREAD

**Issue by BenjaminHamon** [Hydra-Mods/HydraUI#65]
I'm experiencing an issue where my chat window gets filled up with "dummy" frames on each connection and UI reload. These frames are "Chat window ##" with a number (from 7 to 10 right now). No matter the combination of resetting the chat settings, removing the WTF directory, cleaning the windows and switching HydraUI between enabled and disabled, the windows always come back. Furthermore, with HydraUI disabled, the windows appear once but can be removed and will not be created anew, suggesting the issue is caused by HydraUI.

The issue has been occurring since I started playing again, around early September, and I managed to reproduce with a clean WTF directory and the HydraUI at the master revision, and no other addon enabled.

I tried to investigate the issue in `Chat.lua`, without much success. The frames become visible during the call to `MoveChatFrames`, yet they seem to exist even prior to `Chat:Load`. I can't tell if HydraUI is creating new frames or forcing all possible frames to be visible, as there does not appear to be code that does that. The `Install` function requires a UI reload, so it's hard to tell if it is in any way related.

There has been a few reports on the Discord for this specific issue, and for other problems with the chat, notably the chat settings not saving. Perhaps there is a root cause there, although personally my only issue has been the new frames coming back every time, the frames I create and modify explicitly work fine.

https://discord.com/channels/595743987533348864/597911890253053972/1023555106043613214
https://discord.com/channels/595743987533348864/597911890253053972/1023526390731132978
https://discord.com/channels/595743987533348864/597911890253053972/1023235043398795317

**Comment by BenjaminHamon** [comment]
Here is a screenshot of my chat window:

![image](https://user-images.githubusercontent.com/3974249/193460201-d8bc2a84-14e8-409e-909e-8c9235990741.png)

**Comment by Hydra-Mods** [comment]
Thank you for the report, I've applied a fix that should correct this

**Comment by BenjaminHamon** [comment]
I can confirm the issue is fixed, thanks <3
