### ISSUE TITLE
Shaman totem bar

### ISSUE THREAD

**Issue by CadoCat** [Hydra-Mods/HydraUI#66]
Connected to #60 the totem bar still has a number of issues.
1. The spells for the totems don't show when selected. The icon defaults to the "no totem selected".

2. When switching the "Call of the X" spells, the icons show up in the default Blizzard location:
![image](https://user-images.githubusercontent.com/113401819/194560373-1512d30c-f910-4c51-83fb-2fdb45210337.png)

**Comment by Hydra-Mods** [comment]
Thanks for the report, I got it fixed up now

**Comment by CadoCat** [comment]
Thanks for that. The icons are now updating. The other Calls are still showing the totems in the wrong spot though. Looking at the Blizzard LUA, I'm assuming it has to do with the MultiCastActionBarFrame_Update

[https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/MultiCastActionBarFrame.lua](https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/MultiCastActionBarFrame.lua)

**Comment by Hydra-Mods** [comment]
Is this movement happening when you learn a new totem spell or something?

**Comment by CadoCat** [comment]
It's more the screenshot. The default call is fine. But when swapping to one of the other calls it breaks the totem bar and the icons appear at their default location (on the left in the screenshot).

**Comment by CadoCat** [comment]
I've looked into this a bit more. Buttons 1-4 are for Call of the Elements, 5-8 are Call of the Ancestors, and 9-12 are spirits.

The issue is the code is only applying on buttons 1-4 and the pages aren't updating so it doesn't get applied when swapping calls.

**Comment by Hydra-Mods** [comment]
Thanks for the research, i'll give it a look. What are call of ancestors/spirits? I only have a low level shaman to test with

**Comment by CadoCat** [comment]
They're the first button on the standard Totembar for wrath. The MultiCastSummonSpellButton, They basically have saved totem sets that a player can place the 4 totems at once.

[Call of the Elements](https://www.wowhead.com/wotlk/spell=66842) @ level 30
[Call of the Ancestors](https://www.wowhead.com/wotlk/spell=66843) @ level 40
[Call of the Spirits](https://www.wowhead.com/wotlk/spell=66844) @ level 50

**Comment by Hydra-Mods** [comment]
Right on, thanks. I'll have a look and get it adapted for all the levels. I added your pvp micro button and aura adjustments too

**Comment by Hydra-Mods** [comment]
I got onto the wrath PTR and was able to get the paging all sorted out. If I missed anything about it please just let me know
