### ISSUE TITLE
Color error when I get close to other players.

### ISSUE THREAD

**Issue by nedempst** [Hydra-Mods/HydraUI#71]
![image](https://user-images.githubusercontent.com/59960468/195248925-40dbf7dd-6d8e-438b-a063-d70c81c75ee4.png)
![image](https://user-images.githubusercontent.com/59960468/195248936-ab987f37-e9a4-488d-a122-4fa0ee3e6fa3.png)
![image](https://user-images.githubusercontent.com/59960468/195248957-187df61a-1593-42f8-b2f3-7bc4650aa8d2.png)

**Comment by Hydra-Mods** [comment]
Is this in shadowlands or dragonflight?

**Comment by nedempst** [comment]
dragonflight only only have it enabled in there :)

**Comment by Hydra-Mods** [comment]
Thanks for the report, I'll get on the beta tomorrow and look at the errors

**Comment by nedempst** [comment]
No worries like the UI and might switch at least partially to it for the
expansion trying to keep the addons minimal.

I put some suggestions into the discord, would love to see some more
options to clean up the nameplates and such.

Anyway, take care for now :)
