### ISSUE TITLE
StanceBarFrame blocking clicks

### ISSUE THREAD

**Issue by thurin** [Hydra-Mods/HydraUI#73]
Lots of reports of having to roll back to 1.83 due to left part of screen no longer accepting clicks.  Looks like a change to stance bar in https://github.com/Hydra-Mods/HydraUI/commit/d03340f65024a8184be346da8c51d8f9970b7a30 is the cause.  If I comment out `	StanceBarFrame:SetAllPoints(self.StanceBar)` the issue goes away.

![image](https://user-images.githubusercontent.com/29006698/196556424-4da05653-5ac9-4943-b51f-cbe31bd35eb2.png)

**Comment by Hydra-Mods** [comment]
Got it fixed up for now - This change was made for the dragonflight beta but the servers are down atm so I'll make a proper fix for both versions when the servers return. Thank you!
