### ISSUE TITLE
minimap and player health/mana bar never activates on shaman

### ISSUE THREAD

**Issue by devomacdee** [Hydra-Mods/HydraUI#74]
Using the same profile from other characters, minimap and palyer health/mana is in hui style.

On shaman neither are ever shown in hui style, they are set to active in the hui options though.

![image](https://user-images.githubusercontent.com/19351529/197776452-1096cc54-c200-4731-9293-f4b5a587b144.png)
![image](https://user-images.githubusercontent.com/19351529/197776545-918ff3b2-0bf6-4968-be64-1e47f669861f.png)
![image](https://user-images.githubusercontent.com/19351529/197776641-15c27e87-ac97-4de1-bac8-a43dcbc8e2ef.png)

**Comment by devomacdee** [comment]
I restarted game and it is working fine now.

**Comment by Hydra-Mods** [comment]
Hey there, if this happens again you can enter this into your chat to display the error that's occuring

/console scriptErrors 1

I'll see if I can find anything out about what happened, thanks for the report
