### ISSUE TITLE
Minimap Button Bar not functioning

### ISSUE THREAD

**Issue by Landelor** [Hydra-Mods/HydraUI#77]
Message: bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
Time: Fri Nov  4 22:34:42 2022
Count: 1
Stack: bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
[string "=[C]"]: in function `CreateTexture'
[string "@Interface/AddOns/HydraUI/Elements/MiniMapButtons.lua"]:177: in function `SkinButtons'
[string "@Interface/AddOns/HydraUI/Elements/MiniMapButtons.lua"]:237: in function <Interface/AddOns/HydraUI/Elements/MiniMapButtons.lua:235>

Locals: (*temporary) = "bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))"

I have to disable Minimap buttons for all addons.

**Comment by Hydra-Mods** [comment]
Thanks for the report, I've added a fix that will be in the next release!
