### ISSUE TITLE
Talking Head not hiding.

### ISSUE THREAD

**Issue by Landelor** [Hydra-Mods/HydraUI#78]
Not sure on this one.
It doesn't even show in the position that HydraUI has it's frame.

I've been trying to figure out what's causing this, even re-installed wow and all addons.
Same behaviour.
Black Talking Head frame behind the Unit Frames.

**Comment by Landelor** [comment]
Screen Cap of the Talking Head issue:
![WoWScrnShot_110422_224532](https://user-images.githubusercontent.com/8555004/200003700-abd4e952-7ad6-4b84-9090-d68ca06fcdfc.jpg)

**Comment by Cymiryc** [comment]
![WoWScrnShot_110422_145856](https://user-images.githubusercontent.com/117463693/200007011-fdfe3627-cd77-4825-b2b7-d97adbec05a3.jpg)
I have the same issue above, talking head frame is up top but it appears behind the action bars

**Comment by Hydra-Mods** [comment]
Thanks for the report, this looks like something was simply changed about the anchoring from Blizzards side, and should be an easy fix

**Comment by Hydra-Mods** [comment]
This is fixed for the next release
