### ISSUE TITLE
Action Bars keep popping back up.

### ISSUE THREAD

**Issue by Landelor** [Hydra-Mods/HydraUI#79]
Not matter how many times I disable them in the WoW options, action bars 6, 7, 8 pop back up on the side after a few reloads.

**Comment by Cymiryc** [comment]
I have this issue too. 
6,7,8 cannot be separated but when hidden in the wow options, they do reappear after a reload ui is done

**Comment by Hydra-Mods** [comment]
Sorry for the inconvenience. These 3 bars didn't have settings yet within the UI - I just added them for the next release and they'll work the same as the others, just use the settings within /hui > Action Bars. Thank you for the report
