### ISSUE TITLE
PetActionButton Error

### ISSUE THREAD

**Issue by Cymiryc** [Hydra-Mods/HydraUI#80]
This error seems to keep popping up. 
As a mage i have hidden/disabled pet bar but it keeps causing an error due to an interface action.

If it persists long enough it appears to be causing stuttering:

5x [ADDON_ACTION_BLOCKED] AddOn 'HydraUI' tried to call the protected function 'PetActionButton1:SetPoint()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPoint'
[string "@Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua"]:150: in function `PositionButtons'
[string "@Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua"]:984: in function <...ce/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:983>
[string "=[C]"]: in function `UpdateGridLayout'
[string "@Interface/FrameXML/ActionBar.lua"]:350: in function `UpdateVisibility'
[string "@Interface/FrameXML/ActionBar.lua"]:317: in function `Hide'
[string "@Interface/FrameXML/PetActionBar.lua"]:182: in function `Update'
[string "@Interface/FrameXML/PetActionBar.lua"]:84: in function <Interface/FrameXML/PetActionBar.lua:70>
[string "=[C]"]: ?

**Comment by Hydra-Mods** [comment]
Thank you for the report, I've applied a fix to this situation for the next release
