### ISSUE TITLE
Combat LUA error

### ISSUE THREAD

**Issue by Landelor** [Hydra-Mods/HydraUI#81]
I keep getting this popup when I enter combat. Not always though.
A reload fixes it. Not sure if this is related to HUI:

`Message: Interface/FrameXML/EditModeSystemTemplates.lua:631: attempt to perform arithmetic on local 'offsetY' (a nil value)
Time: Sat Nov  5 14:01:32 2022
Count: 47
Stack: Interface/FrameXML/EditModeSystemTemplates.lua:631: attempt to perform arithmetic on local 'offsetY' (a nil value)
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:631: in function `GetBottomAnchoredHeight'
[string "@Interface/FrameXML/EditModeUtil.lua"]:40: in function `GetBottomActionBarHeight'
[string "@Interface/FrameXML/UIParent.lua"]:3074: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3104: in function `UIParent_ManageFramePositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:641: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:555: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:655: in function <Interface/FrameXML/EditModeSystemTemplates.lua:648>
[string "=[C]"]: in function `UpdateGridLayout'
[string "@Interface/FrameXML/ActionBar.lua"]:350: in function `UpdateVisibility'
[string "@Interface/FrameXML/ActionBar.lua"]:317: in function `Hide'
[string "@Interface/FrameXML/PetActionBar.lua"]:182: in function `Update'
[string "@Interface/FrameXML/PetActionBar.lua"]:84: in function <Interface/FrameXML/PetActionBar.lua:70>
[string "=[C]"]: ?

Locals: self = MultiBarBottomLeft {
 0 = <userdata>
 buttonPadding = 2
 UpdateSystemSettingAlwaysShowButtons = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:772
 UpdateMagnetismRegistration = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:506
 GetSnapOffsets = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:411
 UpdateFrameStrata = <function> defined @Interface/FrameXML/ActionBar.lua:194
 UpdateButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:669
 IsFrameAnchoredToMe = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:469
 buttonTemplate = "MultiBar1ButtonTemplate"
 ShowBase = <function> defined =[C]:-1
 IsShown = <function> defined @Interface/FrameXML/ActionBar.lua:286
 GetSelectionOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:363
 ResetToDefaultPosition = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:148
 RefreshButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:662
 GetScaledSelectionSides = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:355
 SelectSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:534
 buttonArtDirty = false
 GetFrameMagneticEligibility = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:489
 AddLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:48
 IsBelowFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:322
 UpdateSystemSettingIconSize = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:714
 SetScaleBase = <function> defined =[C]:-1
 HasActiveChanges = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:244
 GetScaledCenter = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:348
 DoesSettingDisplayValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:268
 Layout = <function> defined @Interface/SharedXML/LayoutFrame.lua:333
 settingDisplayInfoMap = <table> {
 }
 addSystemIndexToName = true
 IsLayoutFrame = <function> defined @Interface/SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:263
 MarkDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:90
 ShouldResetSettingsDialogAnchors = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:91
 dirtySe`

**Comment by Hydra-Mods** [comment]
I'll investigate it and see what it's related to

**Comment by Hydra-Mods** [comment]
Fixed in 1.91
