### ISSUE TITLE
Chat box desync (retail only)

### ISSUE THREAD

**Issue by DaddyFatStacks** [Hydra-Mods/HydraUI#82]
Hydra UI chat box doesn't seem to completely override retail's chat box. There is occasional desync shown below. Can't seem to reliably reproduce it, but it happens pretty often.

![image](https://user-images.githubusercontent.com/78206851/202899029-894e0053-ec6f-4842-9afa-75bd9e002261.png)

**Comment by Hydra-Mods** [comment]
Thanks for the report, I've made a change for the next release that should stop this. It should be released later tonight or tomorrow morning
