### ISSUE TITLE
 elements ActionBars - changes to stance bar causing lua

### ISSUE THREAD

**Issue by rhainstorm** [Hydra-Mods/HydraUI#85]
in the menu when i treied to make any changes to teh stance bar, spacing from 2 to 1. size from 32 to 25 etc lua popped. the changes did happen after i did /reload 

Message: ...ce/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:152: attempt to compare nil with number
Time: Mon Nov 21 20:24:07 2022
Count: 223
Stack: ...ce/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:152: attempt to compare nil with number
[string "@Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua"]:152: in function `PositionButtons'
[string "@Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua"]:1654: in function `Hook'
[string "@Interface/AddOns/HydraUI/Elements/GUI/Widgets.lua"]:2216: in function <Interface/AddOns/HydraUI/Elements/GUI/Widgets.lua:2199>

Locals: self = HydraUI Action Bars {
 0 = <userdata>
 Bar6 = HydraUI Action Bar 6 {
 }
 Bar1 = HydraUI Action Bar 1 {
 }
 Loaded = true
 CreateBar7 = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:924
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 Bar1Mover = Frame {
 }
 PetActionBar_Update = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:504
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 ExtraBar = HydraUI Extra Action {
 }
 StanceBar = HydraUI Stance Bar {
 }
 SetCVars = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:1348
 StyleActionButton = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:189
 StylePetActionButton = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:372
 Hide = Frame {
 }
 Bar2 = HydraUI Action Bar 2 {
 }
 Bar7 = HydraUI Action Bar 7 {
 }
 PositionButtons = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:151
 StyleTotemBar = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:1495
 UpdateButtonStatus = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:524
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 CreateBars = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:1264
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 Bar5 = HydraUI Action Bar 5 {
 }
 CreateBar8 = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:973
 CreateBar6 = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:875
 Bar4 = HydraUI Action Bar 4 {
 }
 Disable = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:116
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 CreateBar5 = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:826
 Bar3 = HydraUI Action Bar 3 {
 }
 CreateExtraBar = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:1223
 CreateBar2 = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:679
 Bar8 = HydraUI Action Bar 8 {
 }
 UpdateEmptyButtons = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:1380
 ExtraBarMover = Frame {
 }
 UpdateButtonFont = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:1857
 CreateBar1 = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:597
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 UpdateFlyout = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:1352
 PetBar = HydraUI Pet Bar {
 }
 CreateMovers = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/ActionBars.lua:1315
 PLAYER_REGEN_

**Comment by rhainstorm** [comment]
also happening with adjusting the bag setting 

Message: ...face/AddOns/HydraUI/Elements/ActionBars/BagSlots.lua:200: attempt to index field 'Panel' (a nil value)
Time: Mon Nov 21 21:57:12 2022
Count: 63
Stack: ...face/AddOns/HydraUI/Elements/ActionBars/BagSlots.lua:200: attempt to index field 'Panel' (a nil value)
[string "@Interface/AddOns/HydraUI/Elements/ActionBars/BagSlots.lua"]:200: in function `Hook'
[string "@Interface/AddOns/HydraUI/Elements/GUI/Widgets.lua"]:2216: in function <Interface/AddOns/HydraUI/Elements/GUI/Widgets.lua:2199>

Locals: value = 20
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Panel' (a nil value)"
BagsFrame = HydraUI Bags Frame {
 0 = <userdata>
 Loaded = true
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 Name = "Bags Frame"
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 Objects = <table> {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 UpdateVisibility = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/BagSlots.lua:51
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 Load = <function> defined @Interface/AddOns/HydraUI/Elements/ActionBars/BagSlots.lua:70
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
}
Settings = <table> {
 ab-bar1-button-gap = 1
 XPQuestColor = "CCCC19"
 color-reaction-7 = "009919"
 cooldowns-size = 40
 party-show-debuffs = true
 ab-pet-button-size = 30
 unitframes-player-power-left = "[HealthValues:Short]"
 chat-enable-discord-links = false
 color-reaction-2 = "BF4400"
 color-holy-power = "F2E599"
 tracker-header-font-flags = ""
 tracker-color-normal-highlight = "FFFFFF"
 auras-row-spacing = 16
 ab-pet-per-row = 4
 party-font-flags = ""
 raid-out-of-range = 50
 PetHealthTexture = "HydraUI 4"
 ab-bar7-alpha = 100
 party-spacing = 2
 color-casting-success = "4C9900"
 target-enable-portrait = false
 ab-bar1-button-max = 12
 ab-bar4-alpha = 100
 party-in-range = 100
 auras-count-color = "FAFAFA"
 bags-frame-visiblity = "SHOW"
 ab-bar4-button-gap = 1
 ab-bar3-hover = false
 color-poison = "009900"
 unitframes-boss-health-reverse = false
 chat-tab-font = "PT Sans"
 right-window-size = "SINGLE"
 ab-font-flags = ""
 color-combo-2 = "FFB266"
 minimap-size = 150
 reputation-progress-visibility = "ALWAYS"
 error-font-flags = ""
 raid-pets-health-height = 22
 profile-created-by = "Rixtriel-Thrall"
 unitframes-boss-power-color = "POWER"
 player-overlay-alpha = 30
 unitframes-focus-power-smooth = true
 unitframes-pet-power-smooth = true
 ab-bar1-hover = false
 raid-max-columns = 8
 ab-bar2-button-size = 32
 ab-bar1-button-size = 32
 unitframes-targettarget-enable-power = true
 tracker-module-font-color = "FFE6C0"
 color-other = "FFECC1"
 color-combo-points = "FFF468"
 tooltips-font-flags = ""
 ui-border-thickness = 0
 color-combo-6 = "66FF66"
 chat-bubbles-font = "PT Sans"
 ab-bar8-per-row = 1
 ui-button-font = "PT Sans"
 data-text-extra-middle = "Friends"
 nameplates-enable-target-indicator = true
 ToTHealthTex

**Comment by Hydra-Mods** [comment]
Fixed with the latest update
