### ISSUE TITLE
request/suggestion

### ISSUE THREAD

**Issue by rhainstorm** [Hydra-Mods/HydraUI#86]
could it be possible to add a hide the blizzard buff and debuff windows. since we have the option to show them on the player window and buffs are interactable there. this way we dont have to dl another addon just for that. if not its fine.

thank you for this addon. simple. lite and offers most of the major reasons i did use elvui without all the extra bloat and issues

**Comment by Hydra-Mods** [comment]
This is a good suggestion, and I appreciate your feedback thanks!

**Comment by Hydra-Mods** [comment]
Added in 2.02!
