### ISSUE TITLE
Dragonflight Tooltip Error

### ISSUE THREAD

**Issue by Kewlie** [Hydra-Mods/HydraUI#91]
Hey Hydra,

People in discord are reporting an error in the DragonFlight/Retail part of the tooltip module i can post a picture but as i don;t play retail personally this is the best i can do i have tried to direct them here to create the issue  but alas i don;t see anything been posted

![image](https://user-images.githubusercontent.com/34406478/211741830-31d99127-c1c2-4391-85bd-dd8fa3442943.png)

**Comment by Kewlie** [comment]
version 1.974 should fix this issue

**Comment by Hydra-Mods** [comment]
Thank you for the report, the issue was in the item comparison tooltip. It was fixed and uploaded!
