### ISSUE TITLE
Shaman totem bar doesn't allow to change totems

### ISSUE THREAD

**Issue by devomacdee** [Hydra-Mods/HydraUI#93]
When trying to change totems on the totem bar, it will not actually update the totems. To change totems I need to disable hydra ui.

**Comment by CadoCat** [comment]
To give more info on this; 
Totems can be selected, however the icon usually updates incorrectly or doesn't update at all. The icon will be incorrect but using the relevant call will drop the correct totem.
While in combat, the totem changes don't apply. 

Totembar usually requires a reload on first login to correctly display.

**Comment by CadoCat** [comment]
Has this been fixed? Couldn't see any updated in the code.
