### ISSUE TITLE
Aurawatch.lua - Library file belonging to OuF Library

### ISSUE THREAD

**Issue by Kewlie** [Hydra-Mods/HydraUI#96]
we have an issue with the "aurawatch.lua"  (located: interface/addons/Hydraui/Libs/OUF/Elements/Aurawatch.lua) in the OUF library, for some reason line 62 SetText() is throwing and error while hots are active on the frames
a quick fix to prevent the error is to comment out that line or move the calculation that it is trying to perform into it's own if statement then allow the script to follow on

im not the best at this by any means but here is my attempt 

so that it then becomes
 `if icon.count then
            if count > 1 and count then
            icon.count:SetText()  -- this is line 62
        end
   end`
the error reported is attached for your refrence
[message.txt](https://github.com/Hydra-Mods/HydraUI/files/10519897/message.txt)

**Comment by Kewlie** [comment]
1.982 solves this issue
thanks again hydra

**Comment by Hydra-Mods** [comment]
Thank you for including the error with the report!
