### ISSUE TITLE
The minimap button bar not working [WotLK]

### ISSUE THREAD

**Issue by vadymkedych** [Hydra-Mods/HydraUI#97]
The minimap button bar not working since WotLK Phase 2 patch.
![image](https://user-images.githubusercontent.com/22193315/215139178-489d02d6-eaef-4141-b783-70a7d683e16c.png)

**Comment by Kewlie** [comment]
Is there an error report?, if so im almost certain you have another addon that is interferring with HydraUI

**Comment by vadymkedych** [comment]
> Is there an error report?, if so im almost certain you have another addon that is interferring with HydraUI

No errors in chat at least.

**Comment by vadymkedych** [comment]
Disabled everything but HydraUI, no frame and no buttons at all.
![image](https://user-images.githubusercontent.com/22193315/215266729-1e500d9e-9ae4-42c1-9537-bd1ba06e4642.png)

**Comment by vadymkedych** [comment]
Ok, so it was a Guildbook that interfered with HydraUI. Even with the disabled Guildbook minimap button everything is still messed.
