### ISSUE TITLE
Request: Move frame for the vehicle

### ISSUE THREAD

**Issue by CadoCat** [Hydra-Mods/HydraUI#98]
Just noticed in wrath that I can't move the Vehicle frame (the seating position). I'd fix it myself but I can't find where you did the durability frame.

**Comment by Kewlie** [comment]
cado, did u check out  "HydraUI/Elements/General.lua"

**Comment by CadoCat** [comment]
Yeah I did find it there and tried to replicate it but didn't have much luck.

**Comment by CadoCat** [comment]
So I've found the VehicleSeatIndicator is anchored to the minimap cluster. Not sure but I couldn't unanchor it. I'll keep working on a solution.

**Comment by CadoCat** [comment]
Only workaround I've managed to come up with is to set the size of the minimap cluster to be the same as the minimap plus the upper and lower bars. 

Still not able to re-set the the anchor point. very very frustrating.

**Comment by CadoCat** [comment]
local cap = VehicleSeatIndicator.ClearAllPoints
        local sp = VehicleSeatIndicator.SetPoint
        hooksecurefunc(VehicleSeatIndicator, "SetPoint", function(self)
            cap(self)
            sp(self, "TOPRIGHT", Minimap, "BOTTOMLEFT", 100, -60)
        end)
        
This seems to have resolved the issue. It's messy, but works. Still not sure how to add the mover to it.

**Comment by Hydra-Mods** [comment]
This feature was added in 2.02
Thanks for the request!

**Comment by CadoCat** [comment]
Glad to have have you back fixing the things I'm terrible at!
